[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # This explicitly tells Netlify to install dependencies from the package.json within the functions directory
  # This ensures 'node-fetch' is correctly available
  external_node_modules = ["node-fetch"]
