[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/node-fetch/**"] # Explicitly include node-fetch
  external_node_modules = [] # No external modules if we're including it
